<?php
/**
 * Template for dasboard widget "Soubory ke stažení".
 *
 * @author  Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @link https://github.com/ondrejd/od-downloads-plugin for the canonical source repository
 * @package odwp-downloads_plugin
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit();
}

//...

?>

<p>
    <strong style="color:#f30;">XXX</strong> <code>dashboard-widget-1.phtml</code> (<em>number</em> is <code><?= $number ?></code>).
</p>