<?php
/**
 * Template for configuration of dasboard widget "Soubory ke stažení".
 *
 * @author  Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @link https://github.com/ondrejd/od-downloads-plugin for the canonical source repository
 * @package odwp-downloads_plugin
 * 
 * Used variables (initialized in {@see odwpdp_widget_1::widget()}).
 *
 * @var integer $number
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit();
}

//...

?>
<p class="input-group">
    <label for="odwpdp-number"><?= __( 'Number:', ODWPDP_SLUG ) ?></label>
    <input class="tiny-text" id="odwpdp-number" name="number" type="number" value="<?= $number ?>">
</p>
