<?php
/**
 * Template file for shortcode "Soubory ke stažení".
 *
 * @author  Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-downloads_plugin
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit();
}

/**
 * Used parameters (taken from {@see odwpdp_add_shortcode_1()}).
 *
 * @param array $attrs
 * @param array $files
 */

?><div id="odwpdp-shortcode-1">
    <?php if ( (bool) $attrs['show_title'] === true && ! empty( $attrs['title'] ) ) : ?>
    <h2 class="odwpdp-shortcode-1-title"><?php echo esc_html( $attrs['title'] ); ?></h2>
    <?php endif;?>
    <table style="width: 100%;">
        <thead>
            <tr>
                <th scope="col"><?php _e( 'Název', ODWPDP_SLUG ); ?>
                <th scope="col"><?php _e( 'Datum vyvěšení', ODWPDP_SLUG ); ?>
                <th scope="col"><?php _e( 'Datum stažení', ODWPDP_SLUG ); ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ( $files as $file ) :
            $puton_date  = get_post_meta( $file->ID, 'odwpdp-metabox-1', true );
            $putoff_date = get_post_meta( $file->ID, 'odwpdp-metabox-2', true );
            $file_name   = get_post_meta( $file->ID, 'odwpdp-metabox-3', true );
            $file_info   = odwpdp_get_file_info( $file_name );
        ?>
            <tr>
                <th scope="row">
                    <div class="file-info-cont" style="display: inline-table; height: 52px; vertical-align: middle; min-width: 262px; width: 332px;">
                        <img src="<?php echo $file_info['icon_32']; ?>" class="file-icon" style="display: table-cell; float: left; height: 32px; padding: 10px 0px 10px 0px; position: relative; top: -3px; vertical-align: middle; width: 32px;">
                        <span style="float: left; display: table-cell; height: 52px; padding-left: 10px; text-align: left; vertical-align: middle; min-width: 220px; width: 290px;">
                            <a href="<?php echo $file_info['url']; ?>" class="file-link"><?php echo $file->post_title; ?></a><br>
                            <span class="file-size"><?php printf( __( 'Velikost: %s', ODWPDP_SLUG ), $file_info['size'] ); ?></span>
                        </span>
                    </div>
                </th>
                <td>
                    <?php if ( ! empty( $puton_date ) ) : ?>
                    <?php echo date( 'j.n.Y', strtotime( $puton_date ) ); ?>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ( ! empty( $putoff_date ) ) : ?>
                    <?php echo date( 'j.n.Y', strtotime( $putoff_date ) ); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>