<?php
/**
 * Template file for widget "Soubory ke stažení".
 *
 * @author  Ondřej Doněk, <ondrejd@gmail.com>
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-downloads_plugin
 * 
 * @todo Format dates by WordPress inner function!
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit();
}

/**
 * Used parameters (taken from {@see odwpdp_widget_1::widget()}).
 *
 * @param array $args
 * @param array $instance
 * @param array $files
 */

// Starts widget
echo $args['before_widget'];

// Widget's title
if ( ! empty( $instance['title'] ) ) {
    echo $args['before_title'] . apply_filters( 'widget_title', $instance['title'] ) . $args['after_title'];
}

?>
<div class="odwpdp-widget-1">
    <ul>
        <?php foreach ( $files as $file ) :
            $puton_date  = get_post_meta( $file->ID, 'odwpdp-metabox-1', true );
            $putoff_date = get_post_meta( $file->ID, 'odwpdp-metabox-2', true );
            $file_name   = get_post_meta( $file->ID, 'odwpdp-metabox-3', true );
            $file_info   = odwpdp_get_file_info( $file_name );
        ?>
        <li>
            <div class="file-info-cont-small" style="display: inline-table; height: 52px; vertical-align: middle; width: 262px;">
                <img src="<?php echo $file_info['icon_32']; ?>" class="file-icon" style="display: table-cell; float: left; height: 32px; padding: 10px 0px 10px 0px; position: relative; top: -3px; vertical-align: middle; width: 32px;">
                <span style="float: left; display: table-cell; height: 52px; padding-left: 10px; text-align: left; vertical-align: middle; width: 200px;">
                    <a href="<?php echo $file_info['url']; ?>" class="file-link"><?php echo $file->post_title; ?></a><br>
                    <small class="file-size"><?php echo $file_info['size']; ?></small>
                    &nbsp;|&nbsp;
                    <small class="value" title="<?php _e( 'Datum vyvěšení/sejmutí', ODWPDP_SLUG ); ?>"><?php
                    printf(
                        '%s/%s',
                        ( ! empty( $puton_date ) ) ? date( 'j.n.Y', strtotime( $puton_date ) ) : '---',
                        ( ! empty( $putoff_date ) ) ? date( 'j.n.Y', strtotime( $putoff_date ) ) : '---'
                    );
                    ?></small>
                </span>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php

// Ends widget
echo $args['after_widget'];